### ISSUE TITLE
bibdervalt not rendering bibliography or citations properly

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#192] opened 2016-05-26 04:48 UTC
Ubuntu 14.04 rendering 00_bibdervalt using sh make_paper.sh gives me a pdf, but with no visible references section and `[?]` instead of a reference.

I've ran all the apt-get commands for latex packages listed in the README.

**Comment by stefanv** [comment] 2016-05-26 09:26
I cannot reproduce.

There should be ``[?]`` next to some of the references, if you read the text, but Hume's citation should be intact.

**Comment by rainwoodman** [comment] 2016-05-27 06:43
I thought #184 could have fixed this -- but it has been merged already. What does the latex log file (in output/) say?

**Comment by rainwoodman** [comment] 2016-06-27 05:42
I see. It is because of a recent change to use alphaurl. WHen alphaurl is missing the natbib error is not properly detected.

**Comment by mpacer** [comment] 2017-05-03 21:30
I cannot reproduce on master or on my more recent branches on python3. There are currently errors for running this on python2 on master. But I'm closing this until someone else states that they're running into this issue.

**Closed by mpacer** 2017-05-03 21:30 UTC
